package events

import (
	"testing"

	"github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/assert"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// appsetGeneratedApp builds an Application shaped like one an AppSet Git
// generator would emit in the be-k8s-deployments repo: a Helm source rooted at
// appset/<name>/chart that pulls in the shared common + per-variant value
// files via relative paths.
func appsetGeneratedApp(name, dir string) v1alpha1.Application {
	return v1alpha1.Application{
		ObjectMeta: metav1.ObjectMeta{Name: name},
		Spec: v1alpha1.ApplicationSpec{
			Source: &v1alpha1.ApplicationSource{
				RepoURL:        "https://github.com/placer-engineering/be-k8s-deployments.git",
				Path:           "appset/" + dir + "/chart",
				TargetRevision: "master",
				Helm: &v1alpha1.ApplicationSourceHelm{
					ValueFiles: []string{"../common/values.yaml", "../variants/prod/values.yaml"},
				},
			},
		},
	}
}

// TestAppSetSpecDiffForChange_DropsAppsUnrelatedToChangeList reproduces the
// "stale branch -> flood of unrelated diffs" bug (placer-engineering
// be-k8s-deployments PR 3112). When the PR branch is far behind the base
// branch, the AppSet HEAD render (at the stale PR head) and the base render (at
// the up-to-date base) diverge by everything that changed on the base branch.
// computeAppSetSpecDiff then reports every app present in base-but-not-head as
// "removed by AppSet" — hundreds of apps the PR never touched.
//
// appSetSpecDiffForChange must narrow both sides to apps whose generation
// depends on the PR's changed files, so only the genuinely affected apps
// surface — while still preserving the AppSet handover findings that
// computeAppSetSpecDiff exists for.
func TestAppSetSpecDiffForChange_DropsAppsUnrelatedToChangeList(t *testing.T) {
	logger := zerolog.Nop()

	// The PR adds two new AppSet-generated apps (handover layout) and touches
	// only files under appset/permission-resolver-acceptance-cron/.
	headApps := []v1alpha1.Application{
		appsetGeneratedApp("permission-resolver-acceptance-cron-prod", "permission-resolver-acceptance-cron"),
		appsetGeneratedApp("permission-resolver-acceptance-cron-staging", "permission-resolver-acceptance-cron"),
	}

	// The base render (against the up-to-date base branch) yields hundreds of
	// unrelated apps that exist on the base branch but were not generated by
	// the stale PR head. None of these are touched by the PR.
	baseApps := []v1alpha1.Application{
		appsetGeneratedApp("automation-dashboard-prod", "automation-dashboard"),
		appsetGeneratedApp("automation-incubation-prod", "automation-incubation"),
		appsetGeneratedApp("chat-orchestrator-server-prod", "chat-orchestrator-server"),
	}

	changeList := []string{
		"appset/permission-resolver-acceptance-cron/chart/Chart.yaml",
		"appset/permission-resolver-acceptance-cron/common/values.yaml",
		"appset/permission-resolver-acceptance-cron/variants/prod/values.yaml",
		"appset/permission-resolver-acceptance-cron/variants/staging/values.yaml",
	}

	// Sanity check: without filtering, the diff floods with "removed by AppSet"
	// findings for the unrelated base apps. This documents the buggy behavior.
	unfiltered := computeAppSetSpecDiff(logger, "prod-appset", headApps, baseApps)
	assert.Len(t, unfiltered, len(headApps)+len(baseApps),
		"unfiltered diff should report every head app as added and every base app as removed")

	// The fix: narrow by the change list. Only the two perm-resolver apps the
	// PR actually added should surface, and they must surface as "added by
	// AppSet" (the handover finding computeAppSetSpecDiff exists for).
	findings := appSetSpecDiffForChange(logger, "prod-appset", headApps, baseApps, changeList, "master")

	assert.Len(t, findings, 2, "only the PR's own AppSet-generated apps should produce findings")
	names := make(map[string]string, len(findings))
	for _, f := range findings {
		names[f.AppName] = f.Action
	}
	assert.Equal(t, "added by AppSet", names["permission-resolver-acceptance-cron-prod"])
	assert.Equal(t, "added by AppSet", names["permission-resolver-acceptance-cron-staging"])

	for _, f := range findings {
		assert.NotContains(t, f.Action, "removed",
			"no unrelated app should be reported as removed by AppSet (app=%s)", f.AppName)
	}
}

// TestAppSetSpecDiffForChange_KeepsLegitimateRemoval verifies the filter does
// not over-narrow: when a PR removes an app's variant value file, that app no
// longer renders at HEAD but still renders at base, and the removed file is in
// the change list (it matches the base app's valueFiles), so the "removed by
// AppSet" finding must still surface.
func TestAppSetSpecDiffForChange_KeepsLegitimateRemoval(t *testing.T) {
	logger := zerolog.Nop()

	// PR deletes appset/legacy-service/variants/prod/values.yaml, so the AppSet
	// stops generating legacy-service-prod at HEAD but still does at base.
	var headApps []v1alpha1.Application
	baseApps := []v1alpha1.Application{
		appsetGeneratedApp("legacy-service-prod", "legacy-service"),
		// An unrelated app the PR never touched — must stay filtered out.
		appsetGeneratedApp("automation-dashboard-prod", "automation-dashboard"),
	}

	changeList := []string{"appset/legacy-service/variants/prod/values.yaml"}

	findings := appSetSpecDiffForChange(logger, "prod-appset", headApps, baseApps, changeList, "master")

	assert.Len(t, findings, 1, "only the app whose value file the PR removed should surface")
	assert.Equal(t, "legacy-service-prod", findings[0].AppName)
	assert.Equal(t, "removed by AppSet", findings[0].Action)
}
