package events

import (
	"context"
	"testing"

	"github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/zapier/kubechecks/pkg/affected_apps"
	"github.com/zapier/kubechecks/pkg/container"
	"github.com/zapier/kubechecks/pkg/generator"
	"github.com/zapier/kubechecks/pkg/git"
	"github.com/zapier/kubechecks/pkg/vcs"
)

// sidedGenerator returns different app sets for the head render (PRContext with
// a HeadSHA) and the base render (zero PRContext), which the shared
// MockGenerator helper cannot express.
type sidedGenerator struct {
	head []v1alpha1.Application
	base []v1alpha1.Application
}

func (g sidedGenerator) GenerateApplicationSetApps(
	_ context.Context, _ v1alpha1.ApplicationSet, _ *container.Container, pr generator.PRContext,
) ([]v1alpha1.Application, error) {
	if pr.HeadSHA == "" {
		return g.base, nil
	}
	return g.head, nil
}

func appWithPath(name, path string) v1alpha1.Application {
	return v1alpha1.Application{
		ObjectMeta: metav1.ObjectMeta{Name: name},
		Spec: v1alpha1.ApplicationSpec{
			Source: &v1alpha1.ApplicationSource{Path: path},
		},
	}
}

// A PR that deletes an app's directory makes the AppSet stop generating that
// Application. The live Application is still in the cluster, so the matcher
// finds it from the changed files -- but its source path no longer exists in
// the PR tree, so queueing it can only fail manifest generation. The removal is
// already reported by the "removed by AppSet" spec-diff finding.
func TestGenerateListOfAffectedApps_SkipsAppsRemovedByAppSet(t *testing.T) {
	removed := appWithPath("removed-app", "apps/removed/chart")
	kept := appWithPath("kept-app", "apps/kept/chart")

	appSet := v1alpha1.ApplicationSet{
		TypeMeta:   metav1.TypeMeta{Kind: "ApplicationSet", APIVersion: "argoproj.io/v1alpha1"},
		ObjectMeta: metav1.ObjectMeta{Name: "test-appset"},
	}

	ce := &CheckEvent{
		logger:      zerolog.Nop(),
		pullRequest: vcs.PullRequest{SHA: "headsha", BaseRef: "master"},
		fileList: []string{
			"apps/removed/chart/Chart.yaml",
			"apps/kept/chart/values.yaml",
		},
		affectedItems: affected_apps.AffectedItems{
			// The matcher sees both live Applications via the changed files.
			Applications:    []v1alpha1.Application{removed, kept},
			ApplicationSets: []v1alpha1.ApplicationSet{appSet},
		},
		generator: sidedGenerator{
			head: []v1alpha1.Application{kept},          // no longer generated by the AppSet
			base: []v1alpha1.Application{kept, removed}, // it was, before the PR
		},
		matcher: MockMatcher("AffectedApps", []interface{}{
			affected_apps.AffectedItems{
				Applications:    []v1alpha1.Application{removed, kept},
				ApplicationSets: []v1alpha1.ApplicationSet{appSet},
			},
			nil,
		}),
	}

	err := ce.GenerateListOfAffectedApps(context.Background(), &git.Repo{Directory: t.TempDir()}, "master", MockInitMatcherFn())
	require.NoError(t, err)

	var names []string
	for _, a := range ce.affectedItems.Applications {
		names = append(names, a.Name)
	}

	assert.NotContains(t, names, "removed-app",
		"an app removed by the AppSet must not be queued for manifest generation")
	assert.Contains(t, names, "kept-app",
		"apps the AppSet still generates must still be checked")
}
